#gt915 touchpanel driver
obj-$(CONFIG_GT9XX_SEC_TOUCHPANEL_DRIVER)	+= gt9xx_sec.o
#gt915 update file
obj-$(CONFIG_GT9XX_SEC_TOUCHPANEL_UPDATE)	+= gt9xx_update_sec.o
#debug tool
obj-$(CONFIG_GT9XX_SEC_TOUCHPANEL_DEBUG)	+= goodix_tool_sec.o
