obj-$(CONFIG_ILITEK171XX_DRIVER) += ilitek_ts.o
ilitek_ts-objs := ilitek_drv_qcom.o
ilitek_ts-objs += ilitek_drv_mp_test.o
ilitek_ts-objs += ilitek_drv_main.o
ilitek_ts-objs += ilitek_drv_update.o
ilitek_ts-objs += ilitek_drv_iliproc.o
